services:
  node:
    container_name: gdocs-converter
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # https://stackoverflow.com/a/32785014/232619
      - .:/app
      - /app/node_modules
    command: node ./gdocs2md/scripts/start-express.js
    ports:
      - 3000:3000

  